name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, synchronize] # Optimize PR triggers to run only on PR creation or updates.

permissions:
    contents: write # For pushing tags, package.json, CHANGELOG.md
    issues: write # For creating issues on failure
    pull-requests: write # For commenting on PRs (Netlify deploy previews)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./ # Set default working directory

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for semantic-release

      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Matches Vite requirements
          cache: 'npm'
          cache-dependency-path: ./package-lock.json # Point to lock file

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run tests (optional)
      #   - name: Run Tests
      #     run: npm run test
      #     if: ${{ !env.SKIP_TESTS }}

      # Build frontend
      - name: Build Frontend
        working-directory: ./packages/frontend
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          echo "Checking environment variables:"
          echo "VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY+x}"
          echo "VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN+x}"
          echo "VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID+x}"
          echo "VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET+x}"
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID+x}"
          echo "VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID+x}"
          echo "VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID+x}"
          # Fail if critical variable is unset
          if [ -z "$VITE_FIREBASE_API_KEY" ]; then
            echo "Error: VITE_FIREBASE_API_KEY is not set"
            exit 1
          fi
          npm run build

      # Log Build Output
      - name: Debug Build Output
        working-directory: ./packages/frontend
        run: ls -R dist

      # Deploy Preview to Netlify (on PR)
      - name: Deploy Preview to Netlify
        if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./packages/frontend/dist
          draft: true
          comment-on-pull-request: true

      # Semantic Release (on main push)
      - name: Semantic Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Deploy production (on main push)
      - name: Deploy Production to Netlify
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: ./packages/frontend/dist
          comment-on-commit: true
